name: Deploy

on:

  workflow_dispatch:

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.SSH_USER}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              # Now we have got the access of EC2 and we will start the deploy .
              aws ecr get-login-password  | docker login --username AWS --password-stdin 424334533647.dkr.ecr.eu-west-1.amazonaws.com
              docker-compose -f docker-compose-backend.yml down
              docker-compose -f docker-compose-backend.yml up --detach
              touch .yaron-deploy
              '
